version: "3.7"
networks:
    test_net:
      ipam:
        driver: default
        config:
          - subnet: 10.0.0.0/24

services:
  relay_alice:
    #environment:
      #- RUST_LOG=debug,sync=info,afg=info,libp2p_swarm=info,multistream_select=info,libp2p_core=info,sub-libp2p=info,libp2p_tcp=info,wasm_overrides=info,wasm-heap=info,libp2p_ping=info,runtime=debug
    image: parity/polkadot:v0.9.12
    entrypoint: ""
    command: polkadot --alice --validator --tmp --chain /config/spec.json --port 30333  --unsafe-ws-external --rpc-port=40333 --unsafe-rpc-external --rpc-cors=all --ws-port 9944
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.2

  relay_bob:
    build:
      context: ../../
      dockerfile: ./devops/dockerfiles/node-and-runtime/relay.dockerfile
        #environment:
        #- RUST_LOG=debug,sync=info,afg=info,libp2p_swarm=info,multistream_select=info,libp2p_core=info,sub-libp2p=info,libp2p_tcp=info,wasm_overrides=info,wasm-heap=info,libp2p_ping=info,runtime=debug
    entrypoint: ""
    tty: true
    command: > 
      bash -c "
      curl https://raw.githubusercontent.com/mangata-finance/mangata-node/86d5eda12bc51bd5da71596dd1d707f367e18480/scripts/runner.sh -o /tmp/runner.sh && 
      chmod +x /tmp/runner.sh && 
      /tmp/runner.sh
      polkadot --bob --validator --tmp --chain /config/spec.json --port 30333  --ws-port 9944 --bootnodes /ip4/10.0.0.2/tcp/40333/p2p/AUTO --unsafe-ws-external --unsafe-rpc-external --rpc-cors=all;
      "
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.3


  register:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/node-and-runtime/para.dockerfile
    command: bash -c "sleep 10s && node index.js"
    environment:
      - STATE_FILE=/config/genesis-state
      - WASM_FILE=/config/genesis-wasm
      - COLLATOR_ADDR=ws://10.0.0.2:9944
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.4

  para_alice:
    image: mangatasolutions/mangata-node:latest
    entrypoint: ""
    command: >
      bash -c "
      /mangata/node export-genesis-state > /config/genesis-state;
      /mangata/node export-genesis-wasm > /config/genesis-wasm;
      /mangata/node --alice --collator --force-authoring --tmp --port 30333
      --ws-port 9944 --unsafe-ws-external --unsafe-rpc-external
      --rpc-cors=all -- --execution wasm --chain /config/spec.json
      --port 30334 --ws-port 9945
      "
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.5

  para_bob:
    image: mangatasolutions/mangata-node:latest
    command: >
      --bob --rpc-cors=all 
      --collator --unsafe-ws-external --unsafe-rpc-external  
      --force-authoring --tmp --port 30333 --ws-port 9944 -- 
      --execution wasm --chain /config/spec.json
      --port 30334
    volumes:
      - ./config:/config
    networks:
        test_net:
          ipv4_address: 10.0.0.6

  ui:
    build:
      context: ../../
      dockerfile: devops/dockerfiles/node-and-runtime/ui.dockerfile
    ports:
      - 3000:3000
    networks:
        test_net:
          ipv4_address: 10.0.0.10


